# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/K2_Project/UQ_DAS/RU_n77/RU_n77.srcs/sources_1/ip/xCORE_CPRI_RUn77_REC/xCORE_CPRI_RUn77_REC.xci
# IP: The module: 'xCORE_CPRI_RUn77_REC' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/ip_1/xCORE_CPRI_RUn77_REC_fc32_rs_fec.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xCORE_CPRI_RUn77_REC_fc32_rs_fec || ORIG_REF_NAME==xCORE_CPRI_RUn77_REC_fc32_rs_fec} -quiet] -quiet

# IP: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/ip_0/xCORE_CPRI_RUn77_REC_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xCORE_CPRI_RUn77_REC_gt || ORIG_REF_NAME==xCORE_CPRI_RUn77_REC_gt} -quiet] -quiet

# XDC: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/ip_1/xCORE_CPRI_RUn77_REC_fc32_rs_fec_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xCORE_CPRI_RUn77_REC_fc32_rs_fec || ORIG_REF_NAME==xCORE_CPRI_RUn77_REC_fc32_rs_fec} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/ip_0/synth/xCORE_CPRI_RUn77_REC_gt_ooc.xdc

# XDC: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/ip_0/synth/xCORE_CPRI_RUn77_REC_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xCORE_CPRI_RUn77_REC_gt || ORIG_REF_NAME==xCORE_CPRI_RUn77_REC_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/synth/xCORE_CPRI_RUn77_REC.xdc
# XDC: The top module name and the constraint reference have the same name: 'xCORE_CPRI_RUn77_REC'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/xCORE_CPRI_RUn77_REC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xCORE_CPRI_RUn77_REC'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/K2_Project/UQ_DAS/RU_n77/RU_n77.srcs/sources_1/ip/xCORE_CPRI_RUn77_REC/xCORE_CPRI_RUn77_REC.xci
# IP: The module: 'xCORE_CPRI_RUn77_REC' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/ip_1/xCORE_CPRI_RUn77_REC_fc32_rs_fec.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xCORE_CPRI_RUn77_REC_fc32_rs_fec || ORIG_REF_NAME==xCORE_CPRI_RUn77_REC_fc32_rs_fec} -quiet] -quiet

# IP: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/ip_0/xCORE_CPRI_RUn77_REC_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xCORE_CPRI_RUn77_REC_gt || ORIG_REF_NAME==xCORE_CPRI_RUn77_REC_gt} -quiet] -quiet

# XDC: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/ip_1/xCORE_CPRI_RUn77_REC_fc32_rs_fec_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xCORE_CPRI_RUn77_REC_fc32_rs_fec || ORIG_REF_NAME==xCORE_CPRI_RUn77_REC_fc32_rs_fec} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/ip_0/synth/xCORE_CPRI_RUn77_REC_gt_ooc.xdc

# XDC: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/ip_0/synth/xCORE_CPRI_RUn77_REC_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xCORE_CPRI_RUn77_REC_gt || ORIG_REF_NAME==xCORE_CPRI_RUn77_REC_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/synth/xCORE_CPRI_RUn77_REC.xdc
# XDC: The top module name and the constraint reference have the same name: 'xCORE_CPRI_RUn77_REC'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/K2_Project/UQ_DAS/RU_n77/RU_n77.gen/sources_1/ip/xCORE_CPRI_RUn77_REC/xCORE_CPRI_RUn77_REC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xCORE_CPRI_RUn77_REC'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
